### ISSUE TITLE
Home#new | GET `"/api/v1/root"`

### ISSUE THREAD

**Issue by MelTravelz** [WWC-Hackathon-2023/missing_piece_api#2]
# Get the Homepage / HomeController#new
```
GET "/api/v1/root"
```
Response:

Status: `200`

- Nothing is being sent for the homepage right now, so should we make the route, controller and action?

**Comment by kem247** [comment]
> GET "/api/v1/root"

Hello @MelTravelz  , I asked this question on ChatGPT and it says "If your application's homepage doesn't require any specific API endpoints or data to be sent, there is generally no need to create a dedicated /api/v1/root endpoint.
API endpoints are typically designed to serve specific data or functionality to clients, and they are created based on the specific requirements of your application. If your homepage does not have any specific API-related functionality, it's perfectly fine not to create an endpoint for it.
Instead, you can serve your homepage through the regular routes and controllers of your web application, without the need for an API endpoint.
However, if you later find a specific need for an API endpoint to serve data or functionality related to your homepage (for example, if you decide to incorporate a dynamic feature or data retrieval on your homepage), you can always create one at that time." 

So should we close this issue?
